name: SpaBoii
description: Arctic Spa hot tub bridge for Home Assistant. No MQTT broker required.
version: "2.1.5"
slug: spaboii
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
map:
  - config:rw
options:
  spa_ip: ""
  spa_port: 0
  log_level: "info"
schema:
  spa_ip: str?
  spa_port: int?
  log_level: list(debug|info|warning|error)
